cpims/urls.py
"""
cpims URL Configuration.

Other urls are import
Put here only urls not specific to app
"""
from django.conf.urls import include, url
from django.contrib import admin
from cpovc_auth import urls as auth_urls
from cpovc_registry import urls as registry_urls
from cpovc_forms import urls as forms_urls
from cpovc_reports import urls as reports_urls
from cpovc_gis import urls as gis_urls
from cpovc_api import urls as api_urls
from cpovc_ovc import urls as ovc_urls
from cpovc_settings import urls as settings_urls
from cpovc_manage import urls as manage_urls
from cpovc_help import urls as help_urls
from notifications import urls as noti_urls
from cpovc_ctip import urls as ctip_urls
from cpovc_afc import urls as ac_urls
from django.contrib.auth.views import (
    password_reset_done, password_change, password_change_done)
from cpovc_auth.views import password_reset
from django.views.generic import TemplateView
# For dashboard
from cpovc_dashboard import urls as dashboard_api_urls

from cpovc_access.forms import StrictPasswordChangeForm


urlpatterns = [
    url(r'^admin/', include(admin.site.urls), name='admin'),
    # url(r'^$', 'cpovc_auth.views.log_in', name='home'),
    url(r'^$', 'cpims.views.home', name='home'),
    url(r'^accounts/request/$', 'cpims.views.access', name='access'),
    url(r'^accounts/terms/(?P<id>\d+)/$', 'cpovc_access.views.terms',
        name='terms'),
    url(r'^login/$', 'cpovc_auth.views.log_in', name='login'),
    url(r'^logout/$', 'cpovc_auth.views.log_out', name='logout'),
    url(r'^register/$', 'cpovc_auth.views.register', name='register'),
    url(r'^auth/', include(auth_urls)),
    url(r'^registry/', include(registry_urls)),
    url(r'^forms/', include(forms_urls)),
    url(r'^reports/', include(reports_urls)),
    url(r'^gis/', include(gis_urls)),
    url(r'^api/v1/', include(api_urls)),
    url(r'^ovcare/', include(ovc_urls)),
    url(r'^settings/', include(settings_urls)),
    url(r'^manage/', include(manage_urls)),
    url(r'^help/', include(help_urls)),
    url(r'^forms/ctip/', include(ctip_urls)),
    url(r'^forms/altcare/', include(ac_urls)),
    url(r'^notifications/', include(noti_urls, namespace='notifications')),
    url(r'^dashboard/(?P<did>[A-Z{2}\Z]+)/$',
        'cpovc_registry.views.dashboard', name='dashboard'),
    url(r'^accounts/login/$', 'cpovc_auth.views.log_in', name='login'),
    url(r'^accounts/password/reset/$', password_reset,
        {'template_name': 'registration/password_reset.html'},
        name='password_reset'),
    url(r'^accounts/password/reset/done/$', password_reset_done,
        {'template_name': 'registration/password_reset_done.html'},
        name='password_reset_done'),
    url(r'^accounts/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
        'cpovc_auth.views.reset_confirm', name='password_reset_confirm'),
    url(r'^reset/$', 'cpovc_auth.views.reset', name='reset'),
    url(r'^accounts/password/change/$', password_change,
        {'post_change_redirect': '/accounts/password/change/done/',
         'template_name': 'registration/password_change.html',
         'password_change_form': StrictPasswordChangeForm},
        name='password_change'),
    url(r'^accounts/password/change/done/$', password_change_done,
        {'template_name': 'registration/password_change_done.html'}),
    url(r'^F57665A859FE7CFCDB6C8935196374AD\.txt$',
        TemplateView.as_view(template_name='comodo.txt',
                             content_type='text/plain')),
    url(r'^d/$', 'cpovc_dashboard.views.ovc_dashboard', name='ovc_dashboard'),
    url(r'^d/hivstat/', 'cpovc_dashboard.views.ovc_dashboard_hivstat', name='hivstat_dash'),
    url(r'^d/services/', 'cpovc_dashboard.views.ovc_dashboard_services', name='services_dash'),
    url(r'^d/cm/', 'cpovc_dashboard.views.ovc_dashboard_cm', name='cm_dash'),
    url(r'^api/v2/', include(dashboard_api_urls)),
    url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt',
                                               content_type='text/plain'))]

handler400 = 'cpims.views.handler_400'
handler404 = 'cpims.views.handler_404'
handler500 = 'cpims.views.handler_500'

admin.site.site_header = 'CPIMS Administration'
admin.site.site_title = 'CPIMS administration'
admin.site.index_title = 'CPIMS admin'

cpovc_afc/urls.py
from django.conf.urls import patterns, url

# This should contain urls related to Care reforms ONLY
urlpatterns = patterns(
    # Alternative Care
    'cpovc_afc.views',
    url(r'^$', 'alt_care_home', name='alternative_care'),
    url(r'^new/(?P<case_id>[0-9A-Za-z_\-{32}\Z]+)/$',
        'new_alternative_care', name='new_alt_care'),
    url(r'^view/(?P<case_id>[0-9A-Za-z_\-{32}\Z]+)/$',
        'view_alternative_care', name='view_alt_care'),
    url(r'^edit/(?P<case_id>[0-9A-Za-z_\-{32}\Z]+)/$',
        'edit_alternative_care', name='edit_alt_care'),
    url(r'^(?P<cid>[A-Z{2}\Z]+)/(?P<form_id>\d+[A-Z_\-{1}\Z]+)/(?P<case_id>[0-9A-Za-z_\-{32}\Z]+)/$',
        'alt_care_form', name='alt_care_form'),
)

cpovc_ctip/urls.py
from django.conf.urls import patterns, url

# This should contain urls related to CTiP ONLY
urlpatterns = patterns(
    # Forms Registry
    'cpovc_ctip.views',
    url(r'^$', 'ctip_home', name='ctip_home'),
    url(r'^case/(?P<case_id>[0-9A-Za-z_\-{32}\Z]+)/$',
        'view_ctip_case', name='view_ctip_case'),
    url(r'^form/(?P<form_id>[A-Z{1}\Z]+)/(?P<case_id>[0-9A-Za-z_\-{32}\Z]+)/(?P<id>\d+)/$',
        'ctip_forms', name='ctip_forms'),
    url(r'^form/(?P<form_id>[A-Z{1}\Z]+)/(?P<case_id>[0-9A-Za-z_\-{32}\Z]+)/$',
        'ctip_form', name='ctip_form'),
    url(r'^form/view/(?P<form_id>[A-Z{1}\Z]+)/(?P<case_id>[0-9A-Za-z_\-{32}\Z]+)/$',
        'view_ctip_form', name='view_ctip_form'),
    url(r'^new/(?P<case_id>[0-9A-Za-z_\-{32}\Z]+)/$',
        'new_ctip_case', name='new_ctip_case'),
    url(r'^edit/(?P<case_id>[0-9A-Za-z_\-{32}\Z]+)/$',
        'edit_ctip_case', name='edit_ctip_case'),

)

notifications/urls.py
''' Django notification urls file '''
# -*- coding: utf-8 -*-
from distutils.version import StrictVersion
# pylint: disable=no-name-in-module,import-error

from django import get_version

from . import views

if StrictVersion(get_version()) >= StrictVersion('2.0'):
    from django.urls import re_path as pattern
else:
    from django.conf.urls import url as pattern


urlpatterns = [
    pattern(r'^$', views.notifications_home, name='home'),
    pattern(r'^(?P<id>\d+)/$', views.notifications_read, name='read'),
    pattern(r'^all/$', views.AllNotificationsList.as_view(), name='all'),
    pattern(r'^unread/$', views.UnreadNotificationsList.as_view(), name='unread'),
    pattern(r'^mark-all-as-read/$', views.mark_all_as_read, name='mark_all_as_read'),
    pattern(r'^mark-as-read/(?P<slug>\d+)/$', views.mark_as_read, name='mark_as_read'),
    pattern(r'^mark-as-unread/(?P<slug>\d+)/$', views.mark_as_unread, name='mark_as_unread'),
    pattern(r'^delete/(?P<slug>\d+)/$', views.delete, name='delete'),
    pattern(r'^api/unread_count/$', views.live_unread_notification_count, name='live_unread_notification_count'),
    pattern(r'^api/all_count/$', views.live_all_notification_count, name='live_all_notification_count'),
    pattern(r'^api/unread_list/$', views.live_unread_notification_list, name='live_unread_notification_list'),
    pattern(r'^api/all_list/', views.live_all_notification_list, name='live_all_notification_list'),
]

app_name = 'notifications'

cpovc_auth/forms.py
"""Forms for authentication module."""
from django import forms
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.auth import get_user_model
from django.template import loader
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from .models import AppUser


class RegistrationForm(forms.Form):
    """Registration form."""

    first_name = forms.CharField(widget=forms.TextInput(
        attrs={'placeholder': _('First name'),
               'class': 'form-control',
               'autofocus': 'true'}))
    last_name = forms.CharField(widget=forms.TextInput(
        attrs={'placeholder': _('Last name'),
               'class': 'form-control',
               'autofocus': 'true'}))
    username = forms.CharField(widget=forms.TextInput(
        attrs={'placeholder': _('Username'),
               'class': 'form-control',
               'autofocus': 'true'}))
    password1 = forms.CharField(widget=forms.PasswordInput(
        attrs={'placeholder': _('Password'),
               'class': 'form-control',
               'autofocus': 'true'}))
    password2 = forms.CharField(widget=forms.PasswordInput(
        attrs={'placeholder': _('Re-enter password'),
               'class': 'form-control',
               'autofocus': 'true'}))
    phone_no = forms.CharField(widget=forms.TextInput(
        attrs={'placeholder': _('Phone number'),
               'class': 'form-control',
               'autofocus': 'true'}))
    national_id = forms.IntegerField(widget=forms.TextInput(
        attrs={'placeholder': _('National id number'),
               'class': 'form-control',
               'autofocus': 'true'}))
    list_geolocation_id = forms.IntegerField(widget=forms.TextInput(
        attrs={'placeholder': _('Geo-location'),
               'class': 'form-control',
               'autofocus': 'true'}))
    staff_no = forms.CharField(widget=forms.TextInput(
        attrs={'placeholder': _('Staff number'),
               'class': 'form-control',
               'autofocus': 'true'}))

    def clean_username(self):
        """Method to clean username."""
        try:
            AppUser.objects.get(username__iexact=self.cleaned_data['username'])
        except AppUser.DoesNotExist:
            return self.cleaned_data['username']
        raise forms.ValidationError(_(
            "The username already exists. Please try another one."))

    def clean(self):
        """Method to compare passwords."""
        form_obj = self.cleaned_data
        if 'password1' in form_obj and 'password2' in form_obj:
            if form_obj['password1'] != form_obj['password2']:
                raise forms.ValidationError(
                    _("The two password fields did not match."))
        return self.cleaned_data


class LoginForm(forms.Form):
    """Login form for the application."""

    username = forms.CharField(widget=forms.TextInput(
        attrs={'placeholder': _('Username'),
               'class': 'form-control input-lg',
               'data-parsley-required': "true",
               'data-parsley-error-message': "Please enter your username.",
               'autofocus': 'true'}),
        error_messages={'required': 'Please enter your username.',
                        'invalid': 'Please enter a valid username.'})
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={'placeholder': _('Password'),
               'class': 'form-control input-lg',
               'data-parsley-required': "true",
               'data-parsley-error-message': "Please enter your password.",
               'autofocus': 'true'}),
        error_messages={'required': 'Please enter your password.',
                        'invalid': 'Please enter a valid password.'},)

    def clean_username(self):
        """Method to clean username."""
        username = self.cleaned_data['username']
        if not username:
            raise forms.ValidationError("Please enter your username.")
        return username

    def clean_password(self):
        """Method to clean password."""
        password = self.cleaned_data['password']
        if not password:
            raise forms.ValidationError("Please enter your password.")
        return password


class RolesForm(forms.Form):
    """For generating Roles forms - with predefined groups."""

    acm = 'Access Manager'
    rgm = 'Registry Manager'
    scm = 'System Configuration'
    std = 'Standard logged in'
    swm = 'National child services'
    fa_lg = '<i class="fa fa-info-circle fa-lg"></i>'
    acm_text = ('<a href="#" id="id_ACM" data-toggle="tooltip" title="%s - '
                'This role allows allocation of roles (both restricted and '
                'non-restricted roles) to any user">%s</a>') % (acm, fa_lg)
    rgm_text = ('<a href="#" id="id_RGM" data-toggle="tooltip" title="%s - '
                'This role allows high level administration, de-duplication '
                'and corrections to the national registries (org units, '
                'workforce/users and beneficiaries">%s</a>') % (rgm, fa_lg)
    scm_text = ('<a href="#" id="id_SCM" data-toggle="tooltip" title="%s - '
                'This role allows managing the content of configurable drop '
                'down lists in the system, and maintaining system geographic '
                'data">%s</a>') % (scm, fa_lg)
    std_text = ('<a href="#" id="id_STD" data-toggle="tooltip" title="%s - '
                'This role is allocated by default to all logged in users / '
                'workforce members">%s</a>') % (std, fa_lg)
    ncs_text = ('<a href="#" id="id_SWM" data-toggle="tooltip" title="%s - '
                'This role allows viewing of sensitive individual beneficiary '
                'registry records and forms data throughout the entire '
                'country">%s</a>') % (swm, fa_lg)
    user_id = forms.CharField(widget=forms.HiddenInput)
    group_SCM = forms.BooleanField(label=_('%s %s' % (scm, scm_text)))
    group_RGM = forms.BooleanField(label=_('%s %s' % (rgm, rgm_text)))
    group_ACM = forms.BooleanField(label=_('%s %s' % (acm, acm_text)))
    group_SWM = forms.BooleanField(label=_('%s %s' % (swm, ncs_text)))
    group_STD = forms.BooleanField(label=_('%s %s' % (std, std_text)))
    reset_password = forms.BooleanField()

    ACTIVATE_CHOICES = (('activate', 'Activate (May log into CPIMS)',),
                        ('deactivate', 'Deactivate (May not log into CPIMS)',))
    activate_choice = forms.ChoiceField(
        widget=forms.RadioSelect, choices=ACTIVATE_CHOICES)


class RolesOrgUnits(forms.Form):
    """Form elements for the Roles Org units part."""

    org_unit_id = forms.CharField(widget=forms.HiddenInput)
    org_unit_name = forms.CharField(widget=forms.HiddenInput)
    org_unit_primary = forms.CharField(widget=forms.HiddenInput)
    group_RGU = forms.BooleanField()
    group_DUU = forms.BooleanField()
    group_DSU = forms.BooleanField()
    group_DEC = forms.BooleanField()


class RolesGeoArea(forms.Form):
    """Form elements for the Geo Area part."""

    sub_county = forms.CharField(widget=forms.HiddenInput)
    area_id = forms.CharField(widget=forms.HiddenInput)
    area_welfare = forms.BooleanField(widget=forms.CheckboxInput(
        attrs={'class': 'area_check'}))


class PasswordResetForm(forms.Form):
    """Override method for change password."""

    email = forms.EmailField(label=_("Email"), max_length=254)

    def clean_email(self):
        email = self.cleaned_data['email']
        if not AppUser.objects.filter(
                reg_person__email__iexact=email, is_active=True).exists():
            msg = _("There was error processing your request. Contact Admin.")
            self.add_error('email', msg)
        return email

    def save(self, domain_override=None,
             subject_template_name='registration/password_reset_subject.txt',
             email_template_name='registration/password_reset_email.html',
             use_https=False, token_generator=default_token_generator,
             from_email=None, request=None, html_email_template_name=None):
        """
        To generate a one-use only link for resetting password.

        Then sends to the user.
        """
        from django.core.mail import send_mail
        usermodel = get_user_model()
        email = self.cleaned_data["email"]
        active_users = usermodel._default_manager.filter(
            reg_person__email__iexact=email, is_active=True)
        for user in active_users:
            # Make sure that no email is sent to a user that actually has
            # a password marked as unusable
            if not user.has_usable_password():
                continue
            if not domain_override:
                current_site = get_current_site(request)
                site_name = current_site.name
                domain = current_site.domain
            else:
                site_name = domain = domain_override
            c = {
                'email': user.email,
                'domain': domain,
                'site_name': site_name,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'user': user,
                'token': token_generator.make_token(user),
                'protocol': 'https' if use_https else 'http',
            }
            subject = loader.render_to_string(subject_template_name, c)
            # Email subject *must not* contain newlines
            subject = ''.join(subject.splitlines())
            email = loader.render_to_string(email_template_name, c)

            if html_email_template_name:

templates/registry/roles_edit.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block page_title %} Manage Roles and Permissions {% endblock %}

{% load app_filters %}

{% block primary %}
<!-- begin breadcrumb -->
<ol class="breadcrumb pull-right">
    <li><a href="#">Home</a></li>
    <li class="active">Roles</li>
</ol>
<!-- end breadcrumb -->
<!-- begin page-header -->
<h1 class="page-header">Registry <small>Manage Roles | Person ID : {{ person.id }}</small></h1>
<!-- end page-header -->
{% if messages %}
<div id="messages" class="alert alert-success fade in">
    <span class="close" data-dismiss="alert">×</span>
    <i class="fa fa-check fa-2x pull-left"></i>
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.info %} class="{{ message.info }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
</div>
{% endif %}
{% if message %}
    <div id="messages" class="alert alert-success fade in">
        <span class="close" data-dismiss="alert">×</span>
        <i class="fa fa-check fa-2x pull-left"></i>
        <p class="invalid-form-message"> {{ message }}</p>
    </div>
{% endif %}
<!-- begin row -->
<div class="row">
<!-- Start content area -->
    <div class="col-md-12">
        <!-- begin panel -->
        <form class="form-horizontal form-bordered" action="." method="POST" data-parsley-validate="true" name="form-wizard" id="roles">
        {% csrf_token %}
        {{ form.user_id }}
        <div class="panel panel-inverse">
            <div class="panel-heading">
                <div class="panel-heading-btn">
                    <a href="#" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                </div>
                <h4 class="panel-title">Workforce / user details</h4>
            </div>
            <div class="panel-body">
                <table width="100%" class="table table-profile">
                    <tbody>
                        <tr>
                            <td class="field">Workforce ID</td>
                            <td>{{ person.workforce_id }}</td>
                            <td class="field">First Name</td>
                            <td>{{ person.first_name }}</td>
                            <td class="field">Sex</td>
                            <td>{{ person.sex_id|gen_value:vals }}</td>
                        </tr>
                        <tr>
                            <td class="field">National ID</td>
                            <td>{{ person.national_id }}</td>
                            <td class="field">Surname</td>
                            <td>{{ person.surname }}</td>
                            <td class="field">DOB</td>
                            <td>{{ person.date_of_birth }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <!-- end panel -->
        <!-- begin panel -->
        <div class="panel panel-info">
            <div class="panel-heading">
                <div class="panel-heading-btn">
                    <a href="#" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                </div>
                <h4 class="panel-title">Roles in Organisational unit</h4>
            </div>
            <div class="panel-body">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Organisation Unit</th>
                            <th>Primary parent</th>
                            <th>Registration assistant</th>
                            <th>Document upload</th>
                            <th>Data supervisor</th>
                            <th>Capture site data entry</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for form in formset %}
                        <tr>
                            <td>
                            {{ form.org_unit_id }}
                            {{ form.org_unit_name.value }}
                            </td>
                            <td>{{ form.org_unit_primary.value }}</td>
                            <td>{{ form.group_RGU }}</td>
                            <td>{{ form.group_DUU }}</td>
                            <td>{{ form.group_DSU }}</td>
                            <td>{{ form.group_DEC }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <!-- end panel -->
    </div>
    {% if request.user|has_group:"ACM" or request.user|has_group:"RGU" %}
    <div class="col-md-4">
        <!-- begin panel -->
        <div class="panel panel-info">
            <div class="panel-heading">
                <div class="panel-heading-btn">
                    <a href="#" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                </div>
                <h4 class="panel-title">Role in geographical area</h4>
            </div>
            <div class="panel-body">
                {% if gformset.forms %}
                <table class="table">
                    <thead>
                        <tr>
                            <th>Sub-county</th>
                            <th>Area child services</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td></td>
                            <td><input type="checkbox" id="selecctall"/> Select All</td>
                        </tr>
                        {% for gform in gformset %}
                        <tr>
                            <td>{{ gform.area_id }} {{ gform.sub_county.value }}</td>
                            <td>{{ gform.area_welfare }}</td>
                        </tr>
                        {% endfor %}    
                    </tbody>
                </table>
                {% else %}
                    <p>National level workforce</p>
                {% endif %}
            </div>
        </div>
        <!-- end panel -->
    </div>
    {% endif %}
    <div class="col-md-4">
        <!-- begin panel -->
        <div class="panel panel-info">
            <div class="panel-heading">
                <div class="panel-heading-btn">
                    <a href="#" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                </div>
                <h4 class="panel-title">General system access</h4>
            </div>
            <div class="panel-body">
                <p>{{ form.reset_password }} Reset Password</p>
                <p><input type="password" class="form-control" value="1234" name="default_password"></p>
                {{ form.activate_choice }}
            </div>
        </div>
        <!-- end panel -->
    </div>
    <div class="col-md-4">
        <!-- begin panel -->
        <div class="panel panel-info">
            <div class="panel-heading">
                <div class="panel-heading-btn">
                    <a href="#" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                </div>
                <h4 class="panel-title">Roles non-restricted</h4>
            </div>
            <div class="panel-body roles_non_restricted">
                {% if request.user|has_group:"ACM" and not gformset.forms %}
                <p>{{ form.group_SCM }} {{ form.group_SCM.label|safe }}</p>
                <p>{{ form.group_RGM }} {{ form.group_RGM.label|safe }}</p>
                <p>{{ form.group_ACM }} {{ form.group_ACM.label|safe }}</p>
                {% endif %}
                <p>{{ form.group_STD }} {{ form.group_STD.label|safe }}</p>
            </div>
        </div>
        <!-- end panel -->
    </div> 
    <div class="col-md-12">   
        <div class="panel panel-inverse">
            <div class="panel-body panel-form">
                <div class="form-group">
                    <label class="control-label col-md-4 col-sm-4"></label>
                    <div class="col-md-6 col-sm-6">
                        <p></p>
                        <button type="submit" class="btn btn-primary">Submit</button>
                        <a href="{% url 'search_persons' %}">
                        <button type="button" class="btn btn-default">Cancel</button>
                        </a>
                        <p></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </form>
<!-- End content area -->

</div>
<!-- end row -->
{% endblock %}

{% block lazy_javascript_code %}
<script type="text/javascript">
    jQuery(document).ready(function() {
        //$('.roles_non_restricted').addClass('collapse').removeClass('in');
        $('#id_group_SCM, #id_group_ACM, #id_group_RGM').change(function() {
        var id = $(this).attr('id');
        // Modal to be called here
        confirm_dialogue(id);
        });

        $("#selecctall").change(function(){
            $(".area_check").prop('checked', $(this).prop("checked"));
        });
    });

    function confirm_dialogue(id){
        if (!$('#dataConfirmModal').length) {
            $('body').append('<div id="dataConfirmModal" class="modal fade" role="dialog" aria-labelledby="dataConfirmLabel" aria-hidden="true"><div class="modal-dialog"><div class="modal-content form-horizontal form-bordered"><div class="modal-header"><button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button><h3 id="dataConfirmLabel"></h3></div><div class="modal-body"></div><div class="modal-footer"><button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button><a class="btn btn-primary" id="dataConfirmOK">OK</a></div></div></div></div>');
        }
        var id_label = id.split("_")[2];
        var details = $( "a#id_"+ id_label ).attr( "data-original-title" );
        $('#dataConfirmModal').find('.modal-body').text(details);
        if($('#'+ id).is(':checked')) {
            var txt = ' Please confirm assignment of role';
            var check_val = true;
            var check_val_rev = false;
        }else{
            var txt = ' Please confirm revoking of role';
            var check_val = false;
            var check_val_rev = true;
        }

        $('#dataConfirmModal').find('#dataConfirmLabel').html(txt);
        $('#'+id).prop('checked', check_val_rev);
        $('#dataConfirmOK').click(function(event) {
            $('#'+id).prop('checked', check_val);
            $('#dataConfirmModal').modal('hide');
            return true;
        });
        $('#dataConfirmModal').modal({show:true});
        return false;
    }
</script>

{% endblock %}